### ISSUE TITLE
Function to Edit simsettings.ini

### ISSUE THREAD

**Issue by Auroraah** [xAranaktu/FIFA-19---Career-Mode-Cheat-Table#49]
Can you make it possible to edit the simsettings.ini via Cheat Table? In FIFA 18 I used frosty editor to make some changes to this file to get more realistic results.
Could put a disclaimer in to say you're editing at your own risk, since it can cause havoc with results!

**Comment by xAranaktu** [comment]
At this moment it's not possible. Overall it's possible, but because of the complexity of the settings in this file it will require a few hours to make a CT script which will work. I don't have much free time now and I prefer to focus on other things than importing .ini files into CT. Especially, that frosty will fully support FIFA 19 pretty soon.
